/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Modelo.GestionDeCuentas;
import Modelo.Persona;
import java.util.Vector;

/**
 *
 * @author AleXRD
 */
public class IntroducirParticipante extends javax.swing.JDialog {

    /**
     * Creates new form IntroducirParticipante
     */
    public IntroducirParticipante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NombrePersonaField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ApellidoPersonaField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CIPersonaField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DirecPersonaField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EdadPersonaField = new javax.swing.JTextField();
        Registro = new javax.swing.JButton();
        Error = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 89, 40));

        NombrePersonaField.setBackground(new java.awt.Color(255, 255, 255));
        NombrePersonaField.setForeground(new java.awt.Color(0, 0, 0));
        NombrePersonaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePersonaFieldActionPerformed(evt);
            }
        });
        jPanel2.add(NombrePersonaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 41));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Apellido");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 89, 40));

        ApellidoPersonaField.setBackground(new java.awt.Color(255, 255, 255));
        ApellidoPersonaField.setForeground(new java.awt.Color(0, 0, 0));
        ApellidoPersonaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoPersonaFieldActionPerformed(evt);
            }
        });
        jPanel2.add(ApellidoPersonaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 150, 41));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CI");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 89, 40));

        CIPersonaField.setBackground(new java.awt.Color(255, 255, 255));
        CIPersonaField.setForeground(new java.awt.Color(0, 0, 0));
        CIPersonaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIPersonaFieldActionPerformed(evt);
            }
        });
        jPanel2.add(CIPersonaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 41));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Direccion");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 89, 40));

        DirecPersonaField.setBackground(new java.awt.Color(255, 255, 255));
        DirecPersonaField.setForeground(new java.awt.Color(0, 0, 0));
        DirecPersonaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirecPersonaFieldActionPerformed(evt);
            }
        });
        jPanel2.add(DirecPersonaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 180, 41));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Edad");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 89, 40));

        EdadPersonaField.setBackground(new java.awt.Color(255, 255, 255));
        EdadPersonaField.setForeground(new java.awt.Color(0, 0, 0));
        EdadPersonaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadPersonaFieldActionPerformed(evt);
            }
        });
        jPanel2.add(EdadPersonaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, 41));

        Registro.setBackground(new java.awt.Color(51, 51, 51));
        Registro.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Registro.setForeground(new java.awt.Color(255, 255, 255));
        Registro.setText("Registrar");
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });
        jPanel2.add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 130, 38));

        Error.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        Error.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 250, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Complete los campos para su Registro");
        jLabel5.setDisplayedMnemonicIndex(1);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 370, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 440, 420));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 60, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombrePersonaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePersonaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePersonaFieldActionPerformed

    private void ApellidoPersonaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoPersonaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoPersonaFieldActionPerformed

    private void CIPersonaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIPersonaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CIPersonaFieldActionPerformed

    private void DirecPersonaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirecPersonaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirecPersonaFieldActionPerformed

    private void EdadPersonaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadPersonaFieldActionPerformed
        // TODO add yourndling code here:
    }//GEN-LAST:event_EdadPersonaFieldActionPerformed

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
        // TODO add your handling code here:
        try{
            RevisarHuecos();
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_RegistroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
 public void RevisarHuecos() throws Exception{
        if(NombrePersonaField.getText().isEmpty()||ApellidoPersonaField.getText().isEmpty()||
                CIPersonaField.getText().isEmpty()||DirecPersonaField.getText().isEmpty()||EdadPersonaField.getText().isEmpty()){
            Error.setText("Debe rellenar todos los espacios");
        }
        else{
            Vector<Persona> client = new Vector<Persona>();
            try {
                client = GestionDeCuentas.CargarDatos();	
            }
            catch(Exception ex) {
        	System.out.println("No hay datos");
            }
            
            try{
                String nombre = NombrePersonaField.getText();
                String apellido = ApellidoPersonaField.getText();
                String ci = CIPersonaField.getText();
                String direc = DirecPersonaField.getText();
                int edad = Integer.parseInt(EdadPersonaField.getText());
            
                Persona info = new Persona(nombre,apellido,ci,direc,edad);
            
                client = GestionDeCuentas.Register_Client(info, client);
                
                Error.setText("");
                dispose();
            }
            catch(NumberFormatException x){
                Error.setText("Ha introducido letras en lugar de numeros");
            }
            catch(Exception x){
                Error.setText(x.getMessage());
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroducirParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroducirParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroducirParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroducirParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IntroducirParticipante dialog = new IntroducirParticipante(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoPersonaField;
    private javax.swing.JTextField CIPersonaField;
    private javax.swing.JTextField DirecPersonaField;
    private javax.swing.JTextField EdadPersonaField;
    private javax.swing.JLabel Error;
    private javax.swing.JTextField NombrePersonaField;
    private javax.swing.JButton Registro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
